version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ride-share-postgres
    environment:
      POSTGRES_DB: ride_share
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./safety-schema.sql:/docker-entrypoint-initdb.d/02-safety-schema.sql
      - ./analytics-schema.sql:/docker-entrypoint-initdb.d/03-analytics-schema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ride_share"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ride-share-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ride-share.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 