version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ride_share
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DB_HOST: postgres   # <--- use the service name, not localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ride_share
      DB_PORT: 5432
    depends_on:
      - postgres
    ports:
      - "3000:3000" 